[[postannotation]]
fields=['AC_Orig']
op="max"
name="AC_full"
type="Integer"

[[postannotation]]
fields=['AN_Orig']
op="max"
name="AN_full"
type="Integer"

[[postannotation]]
fields=['AF_Orig']
op="max"
name="AF_full"
type="Float"

[[postannotation]]
fields=['AC']
op="max"
name="AC_cases"
type="Integer"

[[postannotation]]
fields=["AC_full","AC_cases"]
op="lua:AC_full - AC_cases"
name="AC_controls"
type="Integer"